
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenants
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: openshift-stakater-argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: 03-sre/01-dev-test/tenant-operator
    repoURL: 'http://github.com/stakater/gitops-config-template.git'
    targetRevision: option-2
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

