apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Quota
metadata:
  name: large
  annotations:
    quota.tenantoperator.stakater.com/is-default: "false"
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
