
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-prod-review-ui
  namespace: openshift-stakater-argocd
  labels:
    tenant.stakater.com/name: "gabbar"
    env.stakater.com/name: "prod"
    env.stakater.com/kind: "prod"  
spec:
  destination:
    namespace: gabbar-prod
    server: 'https://kubernetes.default.svc'
  project: gabbar-prod
  source:
    path: 01-gabbar/02-review-ui/03-prod
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

