
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-prod-stakater-nordmart-review
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: gabbar-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-gabbar/01-stakater-nordmart-review/03-prod
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: HEAD
  project: gabbar-prod   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

