apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-build-review-ui
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: gabbar-build
    server: 'https://kubernetes.default.svc'
  project: gabbar-build
  source:
    path: 01-gabbar/02-review-ui/00-build
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true