apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-build-stakater-nordmart-reivew
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: gabbar-build
    server: 'https://kubernetes.default.svc'
  project: gabbar-build
  source:
    path: 01-gabbar/01-stakater-nordmart-reivew/00-build
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
