apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: review
    appVersion: SNAPSHOT-PR-36-95336985
    chart: application-0.0.60
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review
    team: stakater
  name: review
  namespace: gabbar-stakater-nordmart-review-pr-36
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: stakater-nordmart-review
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.0.5
  name: review-mongodb
  namespace: gabbar-stakater-nordmart-review-pr-36
secrets:
- name: review-mongodb
---
apiVersion: v1
data:
  DB_NAME: nordmartDB
  JAEGER_ENDPOINT: http://jaeger-collector.istio-system:14268/api/traces
  MONGO_HOST: review-mongodb
kind: ConfigMap
metadata:
  labels:
    app: review
    appVersion: SNAPSHOT-PR-36-95336985
    chart: application-0.0.60
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review
    team: stakater
  name: review
  namespace: gabbar-stakater-nordmart-review-pr-36
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: stakater-nordmart-review
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.0.5
  name: review-mongodb
  namespace: gabbar-stakater-nordmart-review-pr-36
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: review
    appVersion: SNAPSHOT-PR-36-95336985
    chart: application-0.0.60
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review
    team: stakater
  name: review
  namespace: gabbar-stakater-nordmart-review-pr-36
spec:
  ports:
  - name: https
    port: 8080
    targetPort: 8080
  selector:
    app: review
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: stakater-nordmart-review
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.0.5
  name: review-mongodb
  namespace: gabbar-stakater-nordmart-review-pr-36
spec:
  ports:
  - name: mongodb
    nodePort: null
    port: 27017
    targetPort: mongodb
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: stakater-nordmart-review
    app.kubernetes.io/name: mongodb
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: review
    appCategory: backend
    appVersion: SNAPSHOT-PR-36-95336985
    chart: application-0.0.60
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review
    team: stakater
  name: review
  namespace: gabbar-stakater-nordmart-review-pr-36
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: review
        image: nexus-docker-openshift-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review:SNAPSHOT-PR-36-95336985
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: review
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 0.5
            memory: 1Gi
          requests:
            cpu: 0.1
            memory: 128Mi
      imagePullSecrets:
      - name: nexus-docker-config-forked
      serviceAccountName: review
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: stakater-nordmart-review
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.0.5
  name: review-mongodb
  namespace: gabbar-stakater-nordmart-review-pr-36
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: stakater-nordmart-review
      app.kubernetes.io/name: mongodb
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: stakater-nordmart-review
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mongodb
        helm.sh/chart: mongodb-10.0.5
    spec:
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        image: docker.io/bitnami/mongodb:4.4.2-debian-10-r0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: datadir
          subPath: null
      serviceAccountName: review-mongodb
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: review-mongodb
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: review
    appVersion: SNAPSHOT-PR-36-95336985
    chart: application-0.0.60
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: stakater-nordmart-review
    router: default
    team: stakater
  name: review
  namespace: gabbar-stakater-nordmart-review-pr-36
spec:
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: review
    weight: 100
  wildcardPolicy: None
---
apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Space
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: review
    appVersion: SNAPSHOT-PR-36-95336985
    chart: application-0.0.60
    group: com.stakater.platform
    heritage: Helm
    kind: pr
    provider: stakater
    release: stakater-nordmart-review
    team: gabbar
  name: gabbar-stakater-nordmart-review-pr-36
spec:
  tenant: gabbar
