apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: veeru-dev
  namespace: openshift-stakater-argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Veeru team
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: "*"
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-dev
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: openshift-stakater-argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/configs/01-dev/
    repoURL: 'http://github.com/stakater/gitops-config-template.git'
    targetRevision: option-2
    directory:
      recurse: true
  project: veeru-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

