apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Tenant
metadata:
  name: gabbar
spec:
  users:
    owner:
    - nebojsa
    - bilal.bokharee@stakater.com
    edit:
     - sabkat@stakater.com
  quota: medium
  namespacetemplate:
    templateInstances:
    - spec:
        parameters:
        - name: tenant
          value: gabbar
