apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Tenant
metadata:
  name: gabbar
spec:
  users:
    owner:
    - hanzala@stakater.com
    - nebojsa
    - bilal.bokharee@stakater.com
    editor:
     - sabkat@stakater.com
  quota: medium
