apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Tenant
metadata:
  name: gabbar
spec:
  users:
    owner:
    - nebojsa
    - bilal.bokharee@stakater.com
  quota: medium
  namespacetemplate:
    templateInstances:
    - spec:
        template: tenant-vault-access
        parameters:
        - name: tenant
          value: gabbar
      selector:
        matchLabels:
          kind: build, dev, pr
