apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Tenant
metadata:
  name: veeru
spec:
  users:
    owner:
    - nebojsa
    # Test user for Stakater Cloud IAM
    - sro-privileged
  quota: medium
  namespacetemplate:
    templateInstances:
    - spec:
        template: tenant-vault-access    
        parameters:
        - name: tenant
          value: veeru
      selector:
        matchExpressions:
        - {key: kind, operator: In, values: [dev,pr]}
