apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Tenant
metadata:
  name: veeru
spec:
  users:
    owner:
    - nebojsa
    # Test user for Stakater Cloud IAM
    - sro-privileged
    edit:
    - sabkat@stakater.com
  quota: medium
  namespacetemplate:
    templateInstances:
    - spec:
        template: external-secret-template
      selector:
        matchLabels:
          kind: build
    - spec:
        template: nexus-docker-auth-forked
      selector:
        matchLabels:
          kind: build
