apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Tenant
metadata:
  name: veeru
spec:
  users:
    owner:
    - nebojsa
    # Test user for Stakater Cloud IAM
    - sro-privileged
    edit:
    - sabkat@stakater.com
  quota: medium
  namespacetemplate:
    templateInstances:
    - spec:
        parameters:
        - name: tenant
          value: veeru
