
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-review-ui
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: openshift-stakater-argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 01-gabbar/02-review-ui/01-dev
    repoURL: 'http://github.com/stakater/gitops-config-template.git'
    targetRevision: option-2
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

