apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-dev-stakater-nordmart-review-ui
  namespace: openshift-stakater-argocd
  labels:
    tenant.stakater.com/name : "gabbar"  
spec:
  destination:
    namespace: gabbar-dev
    server: 'https://kubernetes.default.svc'
  project: gabbar-dev
  source:
    path: 01-gabbar/02-stakater-nordmart-review-ui/01-dev
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
