apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gabbar-prod
  namespace: openshift-stakater-argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: gabbar team
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: "gabbar-prod"
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-prod
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: openshift-stakater-argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-gabbar/configs/03-prod/
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
    directory:
       recurse: true
  project: gabbar-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true