apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gabbar-build
  namespace: stakater-argocd
spec:
  description: gabbar team
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: "gabbar-build"
    server: https://kubernetes.default.svc
  - namespace: "stakater-argocd"
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gabbar-build
  namespace: stakater-argocd
spec:
  destination:
    namespace: gabbar-build
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-gabbar/configs/00-build/
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
    directory:
       recurse: true
  project: gabbar-build
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
