apiVersion: tronador.stakater.com/v1alpha1 
kind: EnvironmentProvisioner 
metadata:
  name: stakater-nordmart-review-ui-16
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-review-ui
        ref: edf337f859cfcc6b6232181f35d6360f285fcbd8
        path: deploy
      releaseName: edf337f859cfcc6b6232181f35d6360f285fcbd8
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-openshift-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review-ui
              tag: SNAPSHOT-PR-16-edf337f8
