apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: veeru-preview
  namespace: openshift-stakater-argocd
spec:
  description: Veeru team
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: "veeru-*"
    server: https://kubernetes.default.svc
  - namespace: "openshift-stakater-argocd"
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-preview
  namespace: openshift-stakater-argocd
spec:
  destination:
    namespace: openshift-stakater-argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/configs/00-preview/
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
    directory:
      recurse: true
  project: veeru-preview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
